import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { products } from "./products/products";
import styles from './layout.modules.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className={styles.header}>
          <ul className={styles.topLevel}>
            <li className={styles.li}>
              <Link href="/about">About</Link>
              <ul>
                <li className={styles.li}>
                  <Link href="/about/products">Our Products</Link>
                </li>
                <li className={styles.li}>
                  <Link href="/about/us">Us</Link>
                </li>
              </ul>
            </li>
            <li className={styles.li}>
              <Link href="/products">Products list</Link>
              <ul>
                {products.map((product) => (
                  <li className={styles.li} key={product.id}>
                    <Link href={`/products/${product.id}`}>
                      {product.name}
                    </Link>
                  </li>
                ))}
              </ul>
            </li>
          </ul>
        </header>
        {children}
        </body>
    </html>
  );
}
